export type LLM = "Zhi 1" | "Zhi 2" | "Zhi 3" | "Zhi 4";

export interface ProcessingResponse {
  result: string;
  notes?: string;
  mapping?: string;
}

// Mock AI latency and response generation
export async function mockProcess(
  input: string,
  instructions: string,
  functionName: string,
  model: LLM
): Promise<ProcessingResponse> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(generateMockResponse(input, instructions, functionName, model));
    }, 1500);
  });
}

function generateMockResponse(
  input: string,
  instructions: string,
  functionName: string,
  model: LLM
): ProcessingResponse {
  const modelNameMap = {
    "Zhi 1": "Grok",
    "Zhi 2": "Anthropic",
    "Zhi 3": "OpenAI",
    "Zhi 4": "DeepSeek"
  };

  const actualModel = modelNameMap[model];

  if (functionName.includes("Transformation")) {
    return {
      result: `// OUTPUT GENERATED BY ${model.toUpperCase()} (${actualModel})\n// Transformation applied based on: "${instructions}"\n\nNEW PRIMITIVE:\n Line(x, y)\n\nREWRITTEN AXIOMS:\n1. ∀x∀y [Line(x, y) → x ≠ y]\n2. ∀x∀y∀z [Line(x, y) ∧ Line(y, z) → Line(x, z)]`,
      notes: "The transformation preserves the original metric-free models while simplifying the primitive set."
    };
  }

  if (functionName.includes("Schema Equivalence")) {
    return {
      result: `RESULT: EQUIVALENT UP TO DEFINITIONS\n\nProcessed by ${model}`,
      mapping: "Parent(x, y) ≈ Ancestor(x, y)",
      notes: "Schema B is a conservative extension of Schema A."
    };
  }

  return {
    result: `// OUTPUT FROM ${model}\n// Function: ${functionName}\n\nAnalyzing input:\n${input.substring(0, 50)}...\n\nResult:\nAnalysis complete. The logical structure holds under the specified constraints.`,
    notes: `Processed using ${actualModel} inference engine.`
  };
}
