services:
  - type: web
    name: zhi-systems-website
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/journal
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: zhi-systems-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: AZURE_SPEECH_ENDPOINT
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: GOOGLE_SPEECH_API_KEY
        sync: false
    autoDeploy: false

databases:
  - name: zhi-systems-db
    databaseName: zhi_systems
    user: zhi_systems_user
    plan: free
    region: oregon