import { Link } from "wouter";
import { ArrowLeft, Play, Calendar, Clock } from "lucide-react";

interface Podcast {
  id: string;
  title: string;
  description: string;
  audioUrl?: string;
  duration?: string;
  publishedDate: string;
  topics: string[];
}

const podcasts: Podcast[] = [
  {
    id: "borderline-personality-disorder",
    title: "Borderline Personality Disorder",
    description: "An AI-generated deep dive into understanding Borderline Personality Disorder, its symptoms, causes, and treatment approaches.",
    publishedDate: "2025-01-08",
    duration: "25:30",
    topics: ["Psychology", "Mental Health", "Personality Disorders"]
  }
];

export default function Podcasts() {
  return (
    <div className="font-sans bg-white text-gray-900 leading-relaxed min-h-screen">
      {/* Header */}
      <div className="bg-gray-50 border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center gap-4 mb-4">
            <Link href="/">
              <button className="flex items-center gap-2 text-blue-600 hover:text-blue-800">
                <ArrowLeft className="w-4 h-4" />
                Back to Home
              </button>
            </Link>
          </div>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Zhi Systems Podcasts
          </h1>
          <p className="text-lg text-gray-700">
            AI-Generated Audio Content
          </p>
        </div>
      </div>

      {/* About Section */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="mb-8 p-6 bg-green-50 rounded-lg border border-green-200">
          <h2 className="text-xl font-semibold text-green-800 mb-3">About Our AI-Generated Podcasts</h2>
          <p className="text-green-700 leading-relaxed">
            These podcasts are entirely generated by Zhi Systems AI applications. From script writing to voice synthesis, 
            our AI creates engaging, informative audio content on various topics. Each podcast demonstrates the power of 
            fully automated content creation, showcasing advanced AI capabilities in research, writing, and audio production.
          </p>
        </div>

        {/* Podcasts List */}
        <div className="space-y-6">
          {podcasts.map((podcast) => (
            <div key={podcast.id} className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">
                    {podcast.title}
                  </h3>
                  <p className="text-gray-600 mb-3">
                    {podcast.description}
                  </p>
                  
                  {/* Topics */}
                  <div className="flex flex-wrap gap-2 mb-3">
                    {podcast.topics.map((topic) => (
                      <span key={topic} className="px-3 py-1 bg-blue-100 text-blue-800 text-sm rounded-full">
                        {topic}
                      </span>
                    ))}
                  </div>
                  
                  {/* Metadata */}
                  <div className="flex items-center gap-4 text-sm text-gray-500">
                    <div className="flex items-center gap-1">
                      <Calendar className="w-4 h-4" />
                      {new Date(podcast.publishedDate).toLocaleDateString()}
                    </div>
                    {podcast.duration && (
                      <div className="flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        {podcast.duration}
                      </div>
                    )}
                  </div>
                </div>
                
                {/* Play Button */}
                <div className="flex flex-col items-center gap-2 ml-4">
                  {podcast.audioUrl ? (
                    <button className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors">
                      <Play className="w-4 h-4" />
                      Play
                    </button>
                  ) : (
                    <span className="text-sm text-gray-500 italic">Audio Coming Soon</span>
                  )}
                </div>
              </div>
              
              {/* Audio Player */}
              {podcast.audioUrl && (
                <div className="mt-4 pt-4 border-t border-gray-200">
                  <audio controls className="w-full">
                    <source src={podcast.audioUrl} type="audio/mpeg" />
                    Your browser does not support the audio element.
                  </audio>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Coming Soon Notice */}
        <div className="mt-12 text-center p-8 bg-gray-50 rounded-lg">
          <h3 className="text-lg font-semibold text-gray-700 mb-2">More Podcasts Coming Soon</h3>
          <p className="text-gray-600">
            We're continuously generating new AI-powered podcast content. Check back regularly for fresh episodes 
            covering philosophy, psychology, technology, and more.
          </p>
        </div>
      </div>
    </div>
  );
}